-- Seed employees from Treballadors i lloc de treball.xlsx + V2_Orgzanigrama_General_2025.pdf
DELETE FROM employees;
ALTER TABLE employees AUTO_INCREMENT = 1;

INSERT INTO employees (name, role, dept, email, phone, ext, initials, color) VALUES
  ('Alfonso Aguilera Serrano', 'Mecànic', 'Posta en Marxa', '', '', '', 'AA', 'bg-red-400'),
  ('Miquel Agusti Grabulosa', 'Projectes', 'Projectes', '', '', '', 'MA', 'bg-orange-400'),
  ('Jordi Aiguaviva Serra', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'JA', 'bg-amber-400'),
  ('Karim Ajaha Dahan', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'KA', 'bg-yellow-400'),
  ('Joan Alamo Pages', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'JA', 'bg-lime-400'),
  ('Ruben Almansa Pastor', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'RA', 'bg-green-400'),
  ('Noemi Alvarez Gomez', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'NA', 'bg-emerald-400'),
  ('Juan Joaquin Amador Muñoz', 'Mecànic - Soldador', 'Posta en Marxa', '', '', '', 'JA', 'bg-teal-400'),
  ('Albert Amador Valiente', 'Mecànic', 'Posta en Marxa', '', '', '', 'AA', 'bg-cyan-400'),
  ('Ibrahim Amar Touhami El Hasnaoui', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'IA', 'bg-sky-400'),
  ('Pablo Andres Perez', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'PA', 'bg-blue-400'),
  ('Queralt Andreu Rabaña', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'QA', 'bg-indigo-400'),
  ('Igor Andriyiv', 'Mecànic', 'Posta en Marxa', '', '', '', 'IA', 'bg-violet-400'),
  ('Albert Anfruns Cros', 'Projectes', 'Projectes', '', '', '', 'AA', 'bg-purple-400'),
  ('Eliat Ioan Antonie Dejescu', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'EA', 'bg-fuchsia-400'),
  ('Anna Aradas Xargay', 'Administració', 'Administració', '', '', '', 'AA', 'bg-pink-400'),
  ('Ricard Arbat Carandell', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'RA', 'bg-rose-400'),
  ('Raul Arcos Velasco', 'Mecànic', 'Posta en Marxa', '', '', '', 'RA', 'bg-red-400'),
  ('Genis Arderiu Modinos', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'GA', 'bg-orange-400'),
  ('Raimundo Arjona Toledo', 'Mecànic', 'Posta en Marxa', '', '', '', 'RA', 'bg-amber-400'),
  ('Nil Armengol Casali', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'NA', 'bg-yellow-400'),
  ('Manel Armengol Murillo', 'Soldador', 'Posta en Marxa', '', '', '', 'MA', 'bg-lime-400'),
  ('Anass Arrahi Arrai', 'Posta en marxa - I+D', 'I+D', '', '', '', 'AA', 'bg-green-400'),
  ('Rayan Arrahi Arrai', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'RA', 'bg-emerald-400'),
  ('Daniel Artalejo Gimenez', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'DA', 'bg-teal-400'),
  ('Daniel Aulinas Simon', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'DA', 'bg-cyan-400'),
  ('Pau Aumatell Pujol', 'Mecànic', 'Posta en Marxa', '', '', '', 'PA', 'bg-sky-400'),
  ('Mihai Axinia Bernec', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MA', 'bg-blue-400'),
  ('Christian Felipe Ayala Figueroa', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'CA', 'bg-indigo-400'),
  ('Ibrahim Azarfane', 'Elèctric', 'Posta en Marxa', '', '', '', 'IA', 'bg-violet-400'),
  ('Soufian Azouaghe', 'Mecànic', 'Posta en Marxa', '', '', '', 'SA', 'bg-purple-400'),
  ('Amath Ba Ba', 'Premuntatges elèctrics', 'Posta en Marxa', '', '', '', 'AB', 'bg-fuchsia-400'),
  ('Manel Baca Somovilla', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'MB', 'bg-pink-400'),
  ('Ramon Badia Franch', 'Mecànic', 'Posta en Marxa', '', '', '', 'RB', 'bg-rose-400'),
  ('Marçal Bague Bret', 'Elèctric', 'Posta en Marxa', '', '', '', 'MB', 'bg-red-400'),
  ('Matteo Balbo', 'Projectes', 'Projectes', '', '', '', 'MB', 'bg-orange-400'),
  ('Pablo Ballano Ruiz', 'Devolucions', 'Logística', '', '', '', 'PB', 'bg-amber-400'),
  ('Joan Barniol Noguer', 'Tècnic comercial', 'Comercial', '', '', '', 'JB', 'bg-yellow-400'),
  ('Jorge Barrancos Solera', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'JB', 'bg-lime-400'),
  ('Alejandro Barreres Piqueras', 'Mecànic', 'Posta en Marxa', '', '', '', 'AB', 'bg-green-400'),
  ('Michael Jozsef Barrero Pinilla', 'Manteniment', 'Magatzem', '', '', '', 'MB', 'bg-emerald-400'),
  ('Llorenç Barris Font', 'Posta en marxa - I+D', 'I+D', '', '', '', 'LB', 'bg-teal-400'),
  ('Cosme Barris Rodriguez', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'CB', 'bg-cyan-400'),
  ('Miquel Bartrina Cunill', 'Mecànic', 'Posta en Marxa', '', '', '', 'MB', 'bg-sky-400'),
  ('Miquel Batlle Dilme', 'Administració SAT', 'SAT', '', '', '', 'MB', 'bg-blue-400'),
  ('Otman Belhoussain As-salah', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'OB', 'bg-indigo-400'),
  ('John Jairo Beltran Tascon', 'Logística', 'Logística', '', '', '', 'JB', 'bg-violet-400'),
  ('Marc Berga Masoliver', 'OT Mecànica - Ofertes', 'Oficina Tècnica Mecànica', '', '', '', 'MB', 'bg-purple-400'),
  ('Eduardo Esteban Bermudez Rojas', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'EB', 'bg-fuchsia-400'),
  ('Luis Nestor Bernal Perez', 'Mecànic', 'Posta en Marxa', '', '', '', 'LB', 'bg-pink-400'),
  ('Maria Gleva Bernet Casas', 'Administració Depplan', 'Comercial', '', '', '', 'MB', 'bg-rose-400'),
  ('Stefano Bertero Lo Cascio', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'SB', 'bg-red-400'),
  ('Sergi Bertran Gardella', 'Posta en marxa - I+D', 'I+D', '', '', '', 'SB', 'bg-orange-400'),
  ('Labhdeep Bhardwaj Mandle', 'Informàtica', 'Informàtica', '', '', '', 'LB', 'bg-amber-400'),
  ('Jose Antonio Bizarro Antunez', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'JB', 'bg-yellow-400'),
  ('Gerard Blanch Daniel', 'SAT - Comercial', 'SAT', '', '', '', 'GB', 'bg-lime-400'),
  ('David Boadas Carreras', 'Tècnic comercial', 'Comercial', '', '', '', 'DB', 'bg-green-400'),
  ('Pol Boix Castillo', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'PB', 'bg-emerald-400'),
  ('Jordi Boix Peiris', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'JB', 'bg-teal-400'),
  ('Nil Leslie Bokesa Salomon', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'NB', 'bg-cyan-400'),
  ('Toni Bores Pla', 'OT Mecànica - Premuntatges', 'Oficina Tècnica Mecànica', '', '', '', 'TB', 'bg-sky-400'),
  ('Estel Bosch Arbat', 'Posta en marxa - I+D', 'I+D', '', '', '', 'EB', 'bg-blue-400'),
  ('Adrià Bosch Busquets', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'AB', 'bg-indigo-400'),
  ('Ayoub Bouchkhachakh Arbib', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'AB', 'bg-violet-400'),
  ('Marc Bragulat Mir', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MB', 'bg-purple-400'),
  ('Mario Paolo Bravo Cepeda', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'MB', 'bg-fuchsia-400'),
  ('Alvaro Bravo Lopez', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'AB', 'bg-pink-400'),
  ('Nora Brugada Garriga', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'NB', 'bg-rose-400'),
  ('Ramon Maria Brustenga Vilaseca', 'Mecànic', 'Posta en Marxa', '', '', '', 'RB', 'bg-red-400'),
  ('Xavier Busoms Roca', 'Projectes', 'Projectes', '', '', '', 'XB', 'bg-orange-400'),
  ('Albert Busquets Verdaguer', 'Elèctric', 'Posta en Marxa', '', '', '', 'AB', 'bg-amber-400'),
  ('Vicente Cabanes Ribelles', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'VC', 'bg-yellow-400'),
  ('Alex Caceres Hiraldo', 'SAP', 'SAP', '', '', '', 'AC', 'bg-lime-400'),
  ('Mayra Consuelo Caicedo Rodriguez', 'Administració Magatzem', 'Magatzem', '', '', '', 'MC', 'bg-green-400'),
  ('Daniel Calderon Galvez', 'Manteniment', 'Magatzem', '', '', '', 'DC', 'bg-emerald-400'),
  ('Juan Calm Masoliver', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'JC', 'bg-teal-400'),
  ('Icar Calvet Montoya', 'Posta en marxa - I+D', 'I+D', '', '', '', 'IC', 'bg-cyan-400'),
  ('Oriol Calzadilla Fimia', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'OC', 'bg-sky-400'),
  ('Dauda Camara Dansira', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'DC', 'bg-blue-400'),
  ('Pere Canadell Mir', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'PC', 'bg-indigo-400'),
  ('Juan Carlos Caner Garcia Del Valle', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'JC', 'bg-violet-400'),
  ('Antonia Caporale Nita', 'Administració SAT', 'SAT', '', '', '', 'AC', 'bg-purple-400'),
  ('Aniol Carbonell Santanach', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'AC', 'bg-fuchsia-400'),
  ('Albert Carbones Pages', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'AC', 'bg-pink-400'),
  ('Marc Cardona Soler', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'MC', 'bg-rose-400'),
  ('Francisco Javier Carrasco Delgado', 'Elèctric', 'Posta en Marxa', '', '', '', 'FC', 'bg-red-400'),
  ('Alberto Carrera Mariscal', 'Tècnic comercial', 'Comercial', '', '', '', 'AC', 'bg-orange-400'),
  ('Ramon Carrera Fuertes', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'RC', 'bg-amber-400'),
  ('Daniel Carreras Parella', 'Compres Mecanització', 'Mecanització', '', '', '', 'DC', 'bg-yellow-400'),
  ('Pau Carreras Casassas', 'Posta en marxa - I+D', 'I+D', '', '', '', 'PC', 'bg-lime-400'),
  ('Pol Carreras Viñas', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'PC', 'bg-green-400'),
  ('Arnau Casals Pons', 'Projectes', 'Projectes', '', '', '', 'AC', 'bg-emerald-400'),
  ('Carles Casas Casals', 'Mecànic', 'Posta en Marxa', '', '', '', 'CC', 'bg-teal-400'),
  ('Sergi Casellas Gobelin', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'SC', 'bg-cyan-400'),
  ('Arnau Caso Casals', 'Informàtica', 'Informàtica', '', '', '', 'AC', 'bg-sky-400'),
  ('Mateo Castro Holguin', 'Mecànic', 'Posta en Marxa', '', '', '', 'MC', 'bg-blue-400'),
  ('Bogdan Cata', 'Posta en marxa - I+D', 'I+D', '', '', '', 'BC', 'bg-indigo-400'),
  ('Rosa Maria Celma Pujol', 'Administració SAT', 'SAT', '', '', '', 'RC', 'bg-violet-400'),
  ('Muhammed Cham', 'Soldador', 'Posta en Marxa', '', '', '', 'MC', 'bg-purple-400'),
  ('Ivan Chiva Montero', 'Posta en marxa - I+D', 'I+D', '', '', '', 'IC', 'bg-fuchsia-400'),
  ('Ivan Chueco Martinez', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'IC', 'bg-pink-400'),
  ('Rafael Ciorraga Gonzalez', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'RC', 'bg-rose-400'),
  ('Marc Codony Ventura', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'MC', 'bg-red-400'),
  ('Marina Coll Marin', 'Administració RRHH', 'Recursos Humans', '', '', '', 'MC', 'bg-orange-400'),
  ('Sergi Coll Castañer', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'SC', 'bg-amber-400'),
  ('Arnau Collado Cubero', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'AC', 'bg-yellow-400'),
  ('Enrique Colombo Aguade', 'Elèctric', 'Posta en Marxa', '', '', '', 'EC', 'bg-lime-400'),
  ('Biel Colomer Rubio', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'BC', 'bg-green-400'),
  ('Francesc Comajoan Planas', 'Mecànic', 'Posta en Marxa', '', '', '', 'FC', 'bg-emerald-400'),
  ('Pol Comí Porcar', 'Posta en marxa - I+D', 'I+D', '', '', '', 'PC', 'bg-teal-400'),
  ('Gerard Compta Mollà', 'SAT - Mecànic', 'SAT', '', '', '', 'GC', 'bg-cyan-400'),
  ('Angel Conca Hernández', 'Elèctric', 'Posta en Marxa', '', '', '', 'AC', 'bg-sky-400'),
  ('Daniel Contreras Massegú', 'Mecànic', 'Posta en Marxa', '', '', '', 'DC', 'bg-blue-400'),
  ('Arnau Coromina Acuña', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'AC', 'bg-indigo-400'),
  ('Silvia Corominas Exposito', 'Administració SAT', 'SAT', '', '', '', 'SC', 'bg-violet-400'),
  ('Miriam Cortizo Manzano', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'MC', 'bg-purple-400'),
  ('Andreu Costa Camprubi', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'AC', 'bg-fuchsia-400'),
  ('Guillem Costa Vila', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'GC', 'bg-pink-400'),
  ('Llorenç Costa Noguer', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'LC', 'bg-rose-400'),
  ('Urmar Costa Said', 'Elèctric', 'Posta en Marxa', '', '', '', 'UC', 'bg-red-400'),
  ('Jaime Crespo Ruiz', 'Tècnic comercial', 'Comercial', '', '', '', 'JC', 'bg-orange-400'),
  ('Ivan Cruz Fernandez', 'Elèctric', 'Posta en Marxa', '', '', '', 'IC', 'bg-amber-400'),
  ('David Cruz Santoyo', 'SAT - Mecànic', 'SAT', '', '', '', 'DC', 'bg-yellow-400'),
  ('Jesus Cuesta Muñoz', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'JC', 'bg-lime-400'),
  ('Anna Cuevas Senpau', 'Administració Compres', 'Compres', '', '', '', 'AC', 'bg-green-400'),
  ('Denis Cufi Zykov', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'DC', 'bg-emerald-400'),
  ('Marc Cuña Martinez', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'MC', 'bg-teal-400'),
  ('Joan Curos Montero', 'OT Mecanització', 'Mecanització', '', '', '', 'JC', 'bg-cyan-400'),
  ('Artur Konrad Czapiewski', 'Logística', 'Logística', '', '', '', 'AC', 'bg-sky-400'),
  ('Ebrahima Dambelleh Sidibeh', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'ED', 'bg-blue-400'),
  ('Matthieu Daniel Danjon Floquet', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MD', 'bg-indigo-400'),
  ('Petro Darmoriz', 'Mecànic', 'Posta en Marxa', '', '', '', 'PD', 'bg-violet-400'),
  ('Sergi Darnes Contra', 'Posta en marxa - I+D', 'I+D', '', '', '', 'SD', 'bg-purple-400'),
  ('Joel Darnés Cros', 'Posta en marxa - I+D', 'I+D', '', '', '', 'JD', 'bg-fuchsia-400'),
  ('Victor De La Cruz Moreno', 'Mecànic', 'Posta en Marxa', '', '', '', 'VD', 'bg-pink-400'),
  ('Alan De Oliveira Mendoça', 'Mecànic', 'Posta en Marxa', '', '', '', 'AD', 'bg-rose-400'),
  ('Javier Del Egido Perea', 'Posta en marxa - I+D', 'I+D', '', '', '', 'JD', 'bg-red-400'),
  ('Maria Del Viso Tristancho', 'Posta en marxa - I+D', 'I+D', '', '', '', 'MD', 'bg-orange-400'),
  ('Baicro Dembaga Jawneh', 'Mecànic', 'Posta en Marxa', '', '', '', 'BD', 'bg-amber-400'),
  ('Mostafa Dembaga Diagne', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'MD', 'bg-yellow-400'),
  ('Eva Demiquels Batlle', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'ED', 'bg-lime-400'),
  ('Lluc Domenech Llobet', 'Posta en marxa - I+D', 'I+D', '', '', '', 'LD', 'bg-green-400'),
  ('Miquel Domenech Rosell', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'MD', 'bg-emerald-400'),
  ('Artur Dominguez Gispert', 'Posta en marxa - I+D', 'I+D', '', '', '', 'AD', 'bg-teal-400'),
  ('Mike Richard Dos Santos', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'MD', 'bg-cyan-400'),
  ('Albert Dou Vayreda', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'AD', 'bg-sky-400'),
  ('Saibo Drammeh Drammeh', 'Mecànic', 'Posta en Marxa', '', '', '', 'SD', 'bg-blue-400'),
  ('Ebrahima Drammeh Drammeh', 'Mecànic', 'Posta en Marxa', '', '', '', 'ED', 'bg-indigo-400'),
  ('Arnau Duran Ferrero', 'Projectes', 'Projectes', '', '', '', 'AD', 'bg-violet-400'),
  ('Abdesamad El Aoufi', 'Mecànic', 'Posta en Marxa', '', '', '', 'AE', 'bg-purple-400'),
  ('Mohamed El Azzouzi Ainaaissa', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'ME', 'bg-fuchsia-400'),
  ('Mohamed El Bachikhi El Bachiri', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'ME', 'bg-pink-400'),
  ('Rezk El Haraoui Guennioui', 'Tècnic comercial', 'Comercial', '', '', '', 'RE', 'bg-rose-400'),
  ('Aiman El Ouahabi El Oihabi', 'Mecànic', 'Posta en Marxa', '', '', '', 'AE', 'bg-red-400'),
  ('Eduardo Byron Eraso Vela', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'EE', 'bg-orange-400'),
  ('Jordi Espadaler Begara', 'Elèctric', 'Posta en Marxa', '', '', '', 'JE', 'bg-amber-400'),
  ('Ezequiel Nicolas Espinoza', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'EE', 'bg-yellow-400'),
  ('Mª Angels Espuña Llagostera', 'Neteja', 'Administració', '', '', '', 'ME', 'bg-lime-400'),
  ('Nil Espuña Gonzalez', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'NE', 'bg-green-400'),
  ('Mireia Espuña Camprubi', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'ME', 'bg-emerald-400'),
  ('Abdelaziz Essami', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'AE', 'bg-teal-400'),
  ('Isaac Estarriola Camós', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'IE', 'bg-cyan-400'),
  ('Adria Estebanell Garrido', 'Mecànic', 'Posta en Marxa', '', '', '', 'AE', 'bg-sky-400'),
  ('Carles Esteve Villas', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'CE', 'bg-blue-400'),
  ('Marc Fabrega Guillamet', 'Informàtica industrial', 'IT Industrial', '', '', '', 'MF', 'bg-indigo-400'),
  ('Enric Faja Pijuan', 'Administració SAT', 'SAT', '', '', '', 'EF', 'bg-violet-400'),
  ('Angel Farrugia Trasierra', 'Elèctric', 'Posta en Marxa', '', '', '', 'AF', 'bg-purple-400'),
  ('Pau Feixas Geli', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'PF', 'bg-fuchsia-400'),
  ('Jose Manuel Fernandez Gonzalez', 'Mecànic', 'Posta en Marxa', '', '', '', 'JF', 'bg-pink-400'),
  ('Francesc Fernandez Candel', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'FF', 'bg-rose-400'),
  ('Nicolas Fernandez Valera', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'NF', 'bg-red-400'),
  ('Sergio Ferrer Molina', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'SF', 'bg-orange-400'),
  ('Victor Ferreres Sanchez', 'Compres Mecanització', 'Mecanització', '', '', '', 'VF', 'bg-amber-400'),
  ('David Fonollosa Witzke', 'Manteniment', 'Magatzem', '', '', '', 'DF', 'bg-yellow-400'),
  ('Juli Font Buil', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'JF', 'bg-lime-400'),
  ('Jofre Font Casas', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'JF', 'bg-green-400'),
  ('Biel Font Massot', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'BF', 'bg-emerald-400'),
  ('Josep Maria Frigola Aulinas', 'Soldador', 'Posta en Marxa', '', '', '', 'JF', 'bg-teal-400'),
  ('Alain Fuentes Rivas', 'SAP', 'SAP', '', '', '', 'AF', 'bg-cyan-400'),
  ('Monica Gallach Blancafort', 'Validació Ofertes - Costos', 'Costos', '', '', '', 'MG', 'bg-sky-400'),
  ('Soraya Gallardo Bautista', 'Administració SAT', 'SAT', '', '', '', 'SG', 'bg-blue-400'),
  ('Mohamed Yero Gandega Samassa', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MG', 'bg-indigo-400'),
  ('Gerard Garcia Masdeu', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'GG', 'bg-violet-400'),
  ('Benjamin Garcia Cano', 'Mecànic', 'Posta en Marxa', '', '', '', 'BG', 'bg-purple-400'),
  ('Ricardo Garcia Garcia', 'Responsable SAP', 'SAP', '', '', '', 'RG', 'bg-fuchsia-400'),
  ('Guillem Garcia Xarles', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'GG', 'bg-pink-400'),
  ('Francisco Javier Garcia Duran', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'FG', 'bg-rose-400'),
  ('Diego Fernando Santiago Garcia', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'DG', 'bg-red-400'),
  ('Javier Garcia Castro', 'Mecànic', 'Posta en Marxa', '', '', '', 'JG', 'bg-orange-400'),
  ('Jaime Garcia Delgado', 'Mecànic', 'Posta en Marxa', '', '', '', 'JG', 'bg-amber-400'),
  ('Nil Garcia Santamaria', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'NG', 'bg-yellow-400'),
  ('Arnau Gelaberto Juarez', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'AG', 'bg-lime-400'),
  ('Antonie Serban Gheorghe Madalin', 'Elèctric', 'Posta en Marxa', '', '', '', 'AG', 'bg-green-400'),
  ('Isaac Gibert Martinez', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'IG', 'bg-emerald-400'),
  ('Javier Gil Martinez', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'JG', 'bg-teal-400'),
  ('Didac Gimbernat Girgas', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'DG', 'bg-cyan-400'),
  ('Aitor Giralt Lorente', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'AG', 'bg-sky-400'),
  ('Elisabet Gomez Anello', 'Administració', 'Administració', '', '', '', 'EG', 'bg-blue-400'),
  ('Andrea Gomez Pijuan', 'Administració Depplan', 'Comercial', '', '', '', 'AG', 'bg-indigo-400'),
  ('Marc Gonzalez Ubeda', 'SAT - Recanvis / Magatzem', 'SAT', '', '', '', 'MG', 'bg-violet-400'),
  ('Raul Gonzalez Moreno', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'RG', 'bg-purple-400'),
  ('German Gonzalez Garcia', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'GG', 'bg-fuchsia-400'),
  ('Darío Gonzalez Buera', 'Soldador', 'Posta en Marxa', '', '', '', 'DG', 'bg-pink-400'),
  ('Jose Francisco Gonzalez Lema', 'Mecànic', 'Posta en Marxa', '', '', '', 'JG', 'bg-rose-400'),
  ('Ruben Gordillo Luque', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'RG', 'bg-red-400'),
  ('Julià Gracia Sola I Morales', 'Informàtica', 'Informàtica', '', '', '', 'JG', 'bg-orange-400'),
  ('Daniel Graells Vilalta', 'SAT - Elèctric', 'SAT', '', '', '', 'DG', 'bg-amber-400'),
  ('Sergi Grau Carreras', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'SG', 'bg-yellow-400'),
  ('Valeria Grigori', 'Administració SAT', 'SAT', '', '', '', 'VG', 'bg-lime-400'),
  ('Pau Enric Gudayol Teixido', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'PG', 'bg-green-400'),
  ('Antoni Guell Bosch', 'OT Mecanització', 'Mecanització', '', '', '', 'AG', 'bg-emerald-400'),
  ('Claudia Guell Serrat', 'Validació Ofertes - Costos', 'Costos', '', '', '', 'CG', 'bg-teal-400'),
  ('Jordi Güell Mompió', 'OT Mecanització', 'Mecanització', '', '', '', 'JG', 'bg-cyan-400'),
  ('Roger Guilleumas Lloansi', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'RG', 'bg-sky-400'),
  ('Adria Guix Suñer', 'OT Mecànica - Premuntatges', 'Oficina Tècnica Mecànica', '', '', '', 'AG', 'bg-blue-400'),
  ('Jordi Guix Rodeja', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'JG', 'bg-indigo-400'),
  ('Lasana Gumaneh Touray', 'Elèctric', 'Posta en Marxa', '', '', '', 'LG', 'bg-violet-400'),
  ('Bryan Steven Guncha Vivanco', 'Administració', 'Administració', '', '', '', 'BG', 'bg-purple-400'),
  ('Pol Gussinyer Coromina', 'Posta en marxa - I+D', 'I+D', '', '', '', 'PG', 'bg-fuchsia-400'),
  ('Santiago Guzman Turk', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'SG', 'bg-pink-400'),
  ('Pawel Guzowski', 'Mecànic', 'Posta en Marxa', '', '', '', 'PG', 'bg-rose-400'),
  ('Mohamed Haidour Haidour', 'Mecànic', 'Posta en Marxa', '', '', '', 'MH', 'bg-red-400'),
  ('Marouane Hajam El Hammach', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'MH', 'bg-orange-400'),
  ('Mohamed Ayman Hamjan El Achchab Hajji', 'Posta en marxa - I+D', 'I+D', '', '', '', 'MH', 'bg-amber-400'),
  ('Eugen Cristian Harasciuc', 'Elèctric', 'Posta en Marxa', '', '', '', 'EH', 'bg-yellow-400'),
  ('Christian Hernandez Molina', 'Mecànic', 'Posta en Marxa', '', '', '', 'CH', 'bg-lime-400'),
  ('David Herrera Garcia', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'DH', 'bg-green-400'),
  ('Benito Hervas Galeote', 'Elèctric', 'Posta en Marxa', '', '', '', 'BH', 'bg-emerald-400'),
  ('Eduard Hidalgo Vitales', 'Elèctric', 'Posta en Marxa', '', '', '', 'EH', 'bg-teal-400'),
  ('Victor Hiraldo Pareja', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'VH', 'bg-cyan-400'),
  ('Kiryl Holubeu', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'KH', 'bg-sky-400'),
  ('Carles Homs Ferrer', 'Informàtica', 'Informàtica', '', '', '', 'CH', 'bg-blue-400'),
  ('Oriol Hurtado Llenas', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'OH', 'bg-indigo-400'),
  ('Josep Maria Ibañez Font', 'Magatzem', 'Magatzem', '', '', '', 'JI', 'bg-violet-400'),
  ('Jose Miguel Ibañez Alvarado', 'Mecànic', 'Posta en Marxa', '', '', '', 'JI', 'bg-purple-400'),
  ('Eduard Nicolae Ichim', 'Mecànic', 'Posta en Marxa', '', '', '', 'EI', 'bg-fuchsia-400'),
  ('Jordi Iglesias Vilarrasa', 'Posta en marxa - I+D', 'I+D', '', '', '', 'JI', 'bg-pink-400'),
  ('Ebrahima Jallow Sedibeh', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'EJ', 'bg-rose-400'),
  ('Malamini Jamegay Sumareh', 'Mecànic', 'Posta en Marxa', '', '', '', 'MJ', 'bg-red-400'),
  ('Mahamadou Jamegay Sumareh', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'MJ', 'bg-orange-400'),
  ('Hassan Jarari', 'Elèctric', 'Posta en Marxa', '', '', '', 'HJ', 'bg-amber-400'),
  ('Jose Manuel Jimenez Pozo', 'SAT - Recanvis / Magatzem', 'SAT', '', '', '', 'JJ', 'bg-yellow-400'),
  ('Natalia Jimenez Leon', 'OT Mecànica - Simulació', 'Oficina Tècnica Mecànica', '', '', '', 'NJ', 'bg-lime-400'),
  ('Jorgelina Jofre Navarro', 'Administració SAT', 'SAT', '', '', '', 'JJ', 'bg-green-400'),
  ('Nil Juanola Guardiola', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'NJ', 'bg-emerald-400'),
  ('Quim Juanola Pineda', 'Posta en marxa - I+D', 'I+D', '', '', '', 'QJ', 'bg-teal-400'),
  ('Vicenç Juanola Verges', 'Magatzem', 'Magatzem', '', '', '', 'VJ', 'bg-cyan-400'),
  ('Josep Junca Robles', 'Projectes', 'Projectes', '', '', '', 'JJ', 'bg-sky-400'),
  ('Ferran Junca Juanola', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'FJ', 'bg-blue-400'),
  ('Sergi Juvanteny Gimenez', 'OT Mecànica - CME', 'CME', '', '', '', 'SJ', 'bg-indigo-400'),
  ('Adria Juvinyà Serra', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'AJ', 'bg-violet-400'),
  ('Mahamadou Juwara Sumbundu', 'Mecànic', 'Posta en Marxa', '', '', '', 'MJ', 'bg-purple-400'),
  ('Ebrahima Juwara Touray', 'Mecànic', 'Posta en Marxa', '', '', '', 'EJ', 'bg-fuchsia-400'),
  ('Said Kalbouz', 'Mecànic', 'Posta en Marxa', '', '', '', 'SK', 'bg-pink-400'),
  ('Abubakar Kanoute Ndiaye', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'AK', 'bg-rose-400'),
  ('Baraka Kanuteh Samoura', 'Elèctric', 'Posta en Marxa', '', '', '', 'BK', 'bg-red-400'),
  ('Musa Karaga', 'Elèctric', 'Posta en Marxa', '', '', '', 'MK', 'bg-orange-400'),
  ('Mustafa Karaga Karaga', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'MK', 'bg-amber-400'),
  ('Abdoul Karim Cissokho', 'Mecànic', 'Posta en Marxa', '', '', '', 'AK', 'bg-yellow-400'),
  ('Dembo Konteh', 'SAT - Mecànic', 'SAT', '', '', '', 'DK', 'bg-lime-400'),
  ('Julia Kravets', 'Administració RRHH', 'Recursos Humans', '', '', '', 'JK', 'bg-green-400'),
  ('Yury Kuritsyn', 'Projectes', 'Projectes', '', '', '', 'YK', 'bg-emerald-400'),
  ('Dovydas Kuzmickas', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'DK', 'bg-teal-400'),
  ('Axel Lara Sotos', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'AL', 'bg-cyan-400'),
  ('Jordi Legares Cererols', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'JL', 'bg-sky-400'),
  ('Pedro Letamendi Palomeras', 'Tècnic comercial', 'Comercial', '', '', '', 'PL', 'bg-blue-400'),
  ('Francisco Linares Arrabal', 'Magatzem', 'Magatzem', '', '', '', 'FL', 'bg-indigo-400'),
  ('Eduard Llenas Maso', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'EL', 'bg-violet-400'),
  ('Joan Llongarriu Sarbosa', 'Conductor', 'Logística', '', '', '', 'JL', 'bg-purple-400'),
  ('Marti Lloveras Mesas', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'ML', 'bg-fuchsia-400'),
  ('Alejandro Lobato Caballero', 'Mecànic', 'Posta en Marxa', '', '', '', 'AL', 'bg-pink-400'),
  ('Isaac Lopez Cantero', 'Mecànic', 'Posta en Marxa', '', '', '', 'IL', 'bg-rose-400'),
  ('Albert Lopez Villamor', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'AL', 'bg-red-400'),
  ('Pol Lopez Montenegro', 'Informàtica', 'Informàtica', '', '', '', 'PL', 'bg-orange-400'),
  ('Sergio Lopez Elvira', 'Elèctric', 'Posta en Marxa', '', '', '', 'SL', 'bg-amber-400'),
  ('Arnau Lopez Rodriguez', 'Premuntatges elèctrics', 'Posta en Marxa', '', '', '', 'AL', 'bg-yellow-400'),
  ('Javier Lopez Custodio', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'JL', 'bg-lime-400'),
  ('Natalia Escarlata López Kocsis', 'Administració Comercial', 'Comercial', '', '', '', 'NL', 'bg-green-400'),
  ('Alberto Lopez Bueno', 'Administració', 'Administració', '', '', '', 'AL', 'bg-emerald-400'),
  ('Joao Pedro Lopez Da Silva Benetti', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'JL', 'bg-teal-400'),
  ('Miguel Luque Fernandez', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'ML', 'bg-cyan-400'),
  ('Manuel Luque Diaz', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'ML', 'bg-sky-400'),
  ('Yafang Ma', 'Administració Magatzem', 'Magatzem', '', '', '', 'YM', 'bg-blue-400'),
  ('Berta Madorell Serra', 'Posta en marxa - I+D', 'I+D', '', '', '', 'BM', 'bg-indigo-400'),
  ('Lyubov Makhno Atamanyuk', 'Tècnic comercial', 'Comercial', '', '', '', 'LM', 'bg-violet-400'),
  ('Ruslan Mamedov', 'Mecànic', 'Posta en Marxa', '', '', '', 'RM', 'bg-purple-400'),
  ('Harmandeep Mandahar Mandahar', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'HM', 'bg-fuchsia-400'),
  ('Juan Pablo Mantilla Carreño', 'Posta en marxa - I+D', 'I+D', '', '', '', 'JM', 'bg-pink-400'),
  ('Raul Manzano Brioso', 'Elèctric', 'Posta en Marxa', '', '', '', 'RM', 'bg-rose-400'),
  ('Raúl Marco Orti', 'Administració Compres', 'Compres', '', '', '', 'RM', 'bg-red-400'),
  ('Raquel Margüenda Rivas', 'Administració', 'Administració', '', '', '', 'RM', 'bg-orange-400'),
  ('Pedro Antonio Marquez Cedron', 'Elèctric', 'Posta en Marxa', '', '', '', 'PM', 'bg-amber-400'),
  ('David Martin Artacho', 'Elèctric', 'Posta en Marxa', '', '', '', 'DM', 'bg-yellow-400'),
  ('Gerard Martin Aulina', 'Elèctric', 'Posta en Marxa', '', '', '', 'GM', 'bg-lime-400'),
  ('Abel Martinez Dominguez', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'AM', 'bg-green-400'),
  ('Ernest Martinez Casadevall', 'SAP', 'SAP', '', '', '', 'EM', 'bg-emerald-400'),
  ('Francisco Javier Martinez Labrador', 'Projectes', 'Projectes', '', '', '', 'FM', 'bg-teal-400'),
  ('Franco Amaro Martinez Saavedra', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'FM', 'bg-cyan-400'),
  ('Kevin Martinez Solera', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'KM', 'bg-sky-400'),
  ('Iker Martinez Lopez', 'OT Mecànica - Premuntatges', 'Oficina Tècnica Mecànica', '', '', '', 'IM', 'bg-blue-400'),
  ('Marta Martorell Orri', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MM', 'bg-indigo-400'),
  ('Steven Marulanda Aguirre', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'SM', 'bg-violet-400'),
  ('Pau Marzo Ruiz', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'PM', 'bg-purple-400'),
  ('Narcis Masoliver Subiros', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'NM', 'bg-fuchsia-400'),
  ('Maria Asuncion Masoliver Nicolau', 'Administració', 'Administració', '', '', '', 'MM', 'bg-pink-400'),
  ('Juan Ramon Masoliver Nicolau', 'SAT - Mecànic', 'SAT', '', '', '', 'JM', 'bg-rose-400'),
  ('Pau Massip Alfageme', 'Posta en marxa - I+D', 'I+D', '', '', '', 'PM', 'bg-red-400'),
  ('Tomas Matas Nadal', 'Tècnic comercial', 'Comercial', '', '', '', 'TM', 'bg-orange-400'),
  ('Sergio Mateu Valencia', 'Mecànic', 'Posta en Marxa', '', '', '', 'SM', 'bg-amber-400'),
  ('Agustin Matito Martí', 'Mecànic', 'Posta en Marxa', '', '', '', 'AM', 'bg-yellow-400'),
  ('Yuriy Matvyeyev Matvyeyev', 'SAT - Mecànic', 'SAT', '', '', '', 'YM', 'bg-lime-400'),
  ('Jorge Melendez Moreno', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'JM', 'bg-green-400'),
  ('Daniela Melo Vivas', 'Administració OTE', 'Oficina Tècnica Elèctrica', '', '', '', 'DM', 'bg-emerald-400'),
  ('Christian Mena Aguilar', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'CM', 'bg-teal-400'),
  ('Adrià Mendez Garralda', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'AM', 'bg-cyan-400'),
  ('Carlos Menor Lacosta', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'CM', 'bg-sky-400'),
  ('Dorottya Meszaros', 'Administració Compres', 'Compres', '', '', '', 'DM', 'bg-blue-400'),
  ('Jamal Meziane Belaziz', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'JM', 'bg-indigo-400'),
  ('Pau Vicent Micó Gomez', 'Informàtica industrial', 'IT Industrial', '', '', '', 'PM', 'bg-violet-400'),
  ('Xavier Micó Vidal', 'Informàtica', 'Informàtica', '', '', '', 'XM', 'bg-purple-400'),
  ('Nicolau Mir Curos', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'NM', 'bg-fuchsia-400'),
  ('Víctor Miranda Francès', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'VM', 'bg-pink-400'),
  ('Albert Miro Campolier', 'Elèctric', 'Posta en Marxa', '', '', '', 'AM', 'bg-rose-400'),
  ('Brahim Mohamed Massoud', 'Mecànic', 'Posta en Marxa', '', '', '', 'BM', 'bg-red-400'),
  ('Nabil Mohamed Messaoud', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'NM', 'bg-orange-400'),
  ('Antonio Molina Najas', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'AM', 'bg-amber-400'),
  ('Joaquim Moncanut Frigola', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'JM', 'bg-yellow-400'),
  ('Alex Monells Guenes', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'AM', 'bg-lime-400'),
  ('David Montenegro Martinez', 'Posta en marxa - CME', 'CME', '', '', '', 'DM', 'bg-green-400'),
  ('Sergio Mora Gil Poblete', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'SM', 'bg-emerald-400'),
  ('Antonio Morales Lobato', 'Mecànic', 'Posta en Marxa', '', '', '', 'AM', 'bg-teal-400'),
  ('Abel Morató Font', 'Posta en marxa - CME', 'CME', '', '', '', 'AM', 'bg-cyan-400'),
  ('Albert Morejón Pages', 'Informàtica industrial', 'IT Industrial', '', '', '', 'AM', 'bg-sky-400'),
  ('Joel Moreno Sala', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'JM', 'bg-blue-400'),
  ('David Moreno Duran', 'Posta en marxa - I+D', 'I+D', '', '', '', 'DM', 'bg-indigo-400'),
  ('Robert Moreno Perez', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'RM', 'bg-violet-400'),
  ('Eduardo Morera Santomera', 'Compres Mecanització', 'Mecanització', '', '', '', 'EM', 'bg-purple-400'),
  ('Albert Mulero Casadevall', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'AM', 'bg-fuchsia-400'),
  ('Alexander Mumbru Espinosa', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'AM', 'bg-pink-400'),
  ('Lluís Muntada Sala', 'OT Mecànica - CME', 'CME', '', '', '', 'LM', 'bg-rose-400'),
  ('Jaime Muñoz Navajas', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'JM', 'bg-red-400'),
  ('Gerard Muñoz Luceño', 'Posta en marxa - I+D', 'I+D', '', '', '', 'GM', 'bg-orange-400'),
  ('Helena Muñoz Sarraga', 'Administració SAT', 'SAT', '', '', '', 'HM', 'bg-amber-400'),
  ('Cesar Narvaez Rodriguez', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'CN', 'bg-yellow-400'),
  ('Alahaji Saikou Njie Sinnera', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'AN', 'bg-lime-400'),
  ('Samuel Nonell Rocha', 'OT Mecànica - CME', 'CME', '', '', '', 'SN', 'bg-green-400'),
  ('Olga Nonell Rocha', 'Administració', 'Administració', '', '', '', 'ON', 'bg-emerald-400'),
  ('Maria Olea Fernandez', 'Administració Magatzem', 'Magatzem', '', '', '', 'MO', 'bg-teal-400'),
  ('Marcos Olivencia Peña', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'MO', 'bg-cyan-400'),
  ('David Oliveras Ribas', 'Posta en marxa - I+D', 'I+D', '', '', '', 'DO', 'bg-sky-400'),
  ('Sergi Oliveras Roura', 'Compres Mecanització', 'Mecanització', '', '', '', 'SO', 'bg-blue-400'),
  ('Matias Ignacio Ordenes Uribe', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'MO', 'bg-indigo-400'),
  ('Roger Orriols Valls', 'Posta en marxa - I+D', 'I+D', '', '', '', 'RO', 'bg-violet-400'),
  ('Miquel Orriols Montes', 'Elèctric', 'Posta en Marxa', '', '', '', 'MO', 'bg-purple-400'),
  ('Pedro Ortega Obrero', 'OT Mecànica - CME', 'CME', '', '', '', 'PO', 'bg-fuchsia-400'),
  ('Miguel Ortega Obrero', 'Mecànic', 'Posta en Marxa', '', '', '', 'MO', 'bg-pink-400'),
  ('Oriol Ortega Torras', 'Compres Mecanització', 'Mecanització', '', '', '', 'OO', 'bg-rose-400'),
  ('Aitor Ortega Rodriguez', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'AO', 'bg-red-400'),
  ('Marc Padrosa Albert', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MP', 'bg-orange-400'),
  ('Josep Padrosa Clavaguera', 'OT Mecànica - Premuntatges', 'Oficina Tècnica Mecànica', '', '', '', 'JP', 'bg-amber-400'),
  ('Ariadna Pages Trias', 'Administració RRHH', 'Recursos Humans', '', '', '', 'AP', 'bg-yellow-400'),
  ('Arnau Pages Postigo', 'SAP', 'SAP', '', '', '', 'AP', 'bg-lime-400'),
  ('Dario Palacios Gutierrez', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'DP', 'bg-green-400'),
  ('Borja Palaguerri Molina', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'BP', 'bg-emerald-400'),
  ('Aitor Palomanes Jimenez', 'OT Mecànica - Maxpalet (Murlink)', 'Oficina Tècnica Mecànica', '', '', '', 'AP', 'bg-teal-400'),
  ('Valentin Panov', 'Mecànic', 'Posta en Marxa', '', '', '', 'VP', 'bg-cyan-400'),
  ('Noa Pararol Sanchez', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'NP', 'bg-sky-400'),
  ('Francesc Pararols Palomeras', 'Administració Compres', 'Compres', '', '', '', 'FP', 'bg-blue-400'),
  ('Marc Pararols Zaydin', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'MP', 'bg-indigo-400'),
  ('Vladimir Parshin', 'Projectes', 'Projectes', '', '', '', 'VP', 'bg-violet-400'),
  ('Nil Pascual Soler', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'NP', 'bg-purple-400'),
  ('Eduard Pascual Membrado', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'EP', 'bg-fuchsia-400'),
  ('Olga Payola Subirana', 'Administració Depplan', 'Comercial', '', '', '', 'OP', 'bg-pink-400'),
  ('Anna Payola Subirana', 'Administració RRHH', 'Recursos Humans', '', '', '', 'AP', 'bg-rose-400'),
  ('Kilian Pedro Saló', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'KP', 'bg-red-400'),
  ('Aaron Peñas Cruz', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'AP', 'bg-orange-400'),
  ('Michel Denis Pera Hernandez', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MP', 'bg-amber-400'),
  ('Enrique Carlos Perez Gallego', 'Informàtica industrial', 'IT Industrial', '', '', '', 'EP', 'bg-yellow-400'),
  ('Gerard Perez Batlle', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'GP', 'bg-lime-400'),
  ('Yennia Perez Gonzalez', 'Administració Compres', 'Compres', '', '', '', 'YP', 'bg-green-400'),
  ('Alberto Perez - Muelas Noguera', 'Posta en marxa - I+D', 'I+D', '', '', '', 'AP', 'bg-emerald-400'),
  ('Pau Peris Lopez', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'PP', 'bg-teal-400'),
  ('Fabian Aleix Peschke Espi', 'Projectes', 'Projectes', '', '', '', 'FP', 'bg-cyan-400'),
  ('Petro Petrushchak', 'Elèctric', 'Posta en Marxa', '', '', '', 'PP', 'bg-sky-400'),
  ('Marc Picado Portillo', 'Elèctric', 'Posta en Marxa', '', '', '', 'MP', 'bg-blue-400'),
  ('Ramiro Eduardo Pineda Sarango', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'RP', 'bg-indigo-400'),
  ('David Piña Garcia', 'SAT - Mecànic', 'SAT', '', '', '', 'DP', 'bg-violet-400'),
  ('Marc Piquer Mateu', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'MP', 'bg-purple-400'),
  ('Josep Maria Pla Borés', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'JP', 'bg-fuchsia-400'),
  ('Victor Plamadeala', 'Mecànic', 'Posta en Marxa', '', '', '', 'VP', 'bg-pink-400'),
  ('Jaume Plana Ortiz', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'JP', 'bg-rose-400'),
  ('Alba Plana Casademont', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'AP', 'bg-red-400'),
  ('Ricard Polls Boadas', 'Projectes', 'Projectes', '', '', '', 'RP', 'bg-orange-400'),
  ('Eduard Pont Redondo', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'EP', 'bg-amber-400'),
  ('Joan Portabella Puigdemont', 'SAT - Mecànic', 'SAT', '', '', '', 'JP', 'bg-yellow-400'),
  ('Judit Pou Barrés', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'JP', 'bg-lime-400'),
  ('Jordi Pozo Caballero', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'JP', 'bg-green-400'),
  ('Sergi Prat Sevilla', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'SP', 'bg-emerald-400'),
  ('Roger Prat Ferrer', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'RP', 'bg-teal-400'),
  ('Blai Prat Arnau', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'BP', 'bg-cyan-400'),
  ('Arnau Puig Ferrer', 'Administració', 'Administració', '', '', '', 'AP', 'bg-sky-400'),
  ('David Puig Hombrados', 'OT Mecànica - CME', 'CME', '', '', '', 'DP', 'bg-blue-400'),
  ('Berta Puig Capallera', 'Administració RRHH', 'Recursos Humans', '', '', '', 'BP', 'bg-indigo-400'),
  ('Guillem Puig Planas', 'Administració Magatzem', 'Magatzem', '', '', '', 'GP', 'bg-violet-400'),
  ('Pedro Puigdemont Colomer', 'SAT - Mecànic', 'SAT', '', '', '', 'PP', 'bg-purple-400'),
  ('Xavier Puigmal Claravall', 'Elèctric', 'Posta en Marxa', '', '', '', 'XP', 'bg-fuchsia-400'),
  ('Marc Pujadas Ullastres', 'Compres Mecanització', 'Mecanització', '', '', '', 'MP', 'bg-pink-400'),
  ('Anna Pujol Busquets', 'Administració SAT', 'SAT', '', '', '', 'AP', 'bg-rose-400'),
  ('Imma Pujol Badia', 'Administració Comercial', 'Comercial', '', '', '', 'IP', 'bg-red-400'),
  ('Marc Pujolar Repullo', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'MP', 'bg-orange-400'),
  ('Adrian Quesada Lopez', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'AQ', 'bg-amber-400'),
  ('Adria Quintana Tarradas', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'AQ', 'bg-yellow-400'),
  ('Francesc Xavier Rabat Agusti', 'Informàtica industrial', 'IT Industrial', '', '', '', 'FR', 'bg-lime-400'),
  ('Nicolás Ramirez Linares', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'NR', 'bg-green-400'),
  ('Yvan Ramone', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'YR', 'bg-emerald-400'),
  ('Ramon Reguant Izaguirre', 'Tècnic comercial', 'Comercial', '', '', '', 'RR', 'bg-teal-400'),
  ('Tomas Reixach Coll', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'TR', 'bg-cyan-400'),
  ('Arnau Reixach Creus', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'AR', 'bg-sky-400'),
  ('Enric Reverter Cabot', 'Devolucions', 'Logística', '', '', '', 'ER', 'bg-blue-400'),
  ('Lluís Ribas Bach', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'LR', 'bg-indigo-400'),
  ('Carles Ribas Noguer', 'Administració Logística', 'Logística', '', '', '', 'CR', 'bg-violet-400'),
  ('Miquel Ribas Bach', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MR', 'bg-purple-400'),
  ('Tania Ribas Pallé', 'Administració RRHH', 'Recursos Humans', '', '', '', 'TR', 'bg-fuchsia-400'),
  ('Marc Rifa Pereira', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'MR', 'bg-pink-400'),
  ('Josep Ripoll Maresma', 'Posta en marxa - I+D', 'I+D', '', '', '', 'JR', 'bg-rose-400'),
  ('Arnau Risquez Guiteras', 'Posta en marxa - I+D', 'I+D', '', '', '', 'AR', 'bg-red-400'),
  ('Ignasi Riuro Puigvert', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'IR', 'bg-orange-400'),
  ('Alvaro Rivas Reinoso', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'AR', 'bg-amber-400'),
  ('Marc Rodeja Agut', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'MR', 'bg-yellow-400'),
  ('Oscar Rodriguez Garcia', 'Mecànic', 'Posta en Marxa', '', '', '', 'OR', 'bg-lime-400'),
  ('Xavier Rodriguez Sabate', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'XR', 'bg-green-400'),
  ('Paloma Rodriguez Callizo', 'Administració SAT', 'SAT', '', '', '', 'PR', 'bg-emerald-400'),
  ('Marc Roger Sala', 'Posta en marxa - I+D', 'I+D', '', '', '', 'MR', 'bg-teal-400'),
  ('Marina Rom Ostiategui', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'MR', 'bg-cyan-400'),
  ('Patricia Romera Holgado', 'Administració SAT', 'SAT', '', '', '', 'PR', 'bg-sky-400'),
  ('Antonio Romero Montmany', 'Mecànic', 'Posta en Marxa', '', '', '', 'AR', 'bg-blue-400'),
  ('Sergio Romero Gomez', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'SR', 'bg-indigo-400'),
  ('Albert Romero Cano', 'Elèctric', 'Posta en Marxa', '', '', '', 'AR', 'bg-violet-400'),
  ('Isaac Romo Ferrer', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'IR', 'bg-purple-400'),
  ('Pere Lluis Roquera Verges', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'PR', 'bg-fuchsia-400'),
  ('Zenon Rosell López', 'Posta en marxa - I+D', 'I+D', '', '', '', 'ZR', 'bg-pink-400'),
  ('Josep Rotger Goñalons', 'Posta en marxa - I+D', 'I+D', '', '', '', 'JR', 'bg-rose-400'),
  ('Roger Roura Agell', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'RR', 'bg-red-400'),
  ('Fernando Maria Rubi Alzugaray', 'Tècnic comercial', 'Comercial', '', '', '', 'FR', 'bg-orange-400'),
  ('Joan Rubirola Coll', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'JR', 'bg-amber-400'),
  ('Josep Maria Ruiz Perez', 'SAT - Mecànic', 'SAT', '', '', '', 'JR', 'bg-yellow-400'),
  ('Mark Anthony Ruiz Mendoza', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'MR', 'bg-lime-400'),
  ('Jose Luis Ruiz Morales', 'Elèctric', 'Posta en Marxa', '', '', '', 'JR', 'bg-green-400'),
  ('Josep Maria Ruiz Molina', 'Administració RRHH', 'Recursos Humans', '', '', '', 'JR', 'bg-emerald-400'),
  ('Adria Ruvirola Pujol', 'Tècnic mecanitzacio', 'Mecanització', '', '', '', 'AR', 'bg-teal-400'),
  ('Daniel Ruz Fontas', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'DR', 'bg-cyan-400'),
  ('Ilyass Saad Benouahi', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'IS', 'bg-sky-400'),
  ('Mireia Sagué Torrentà', 'OT Mecànica - Premuntatges', 'Oficina Tècnica Mecànica', '', '', '', 'MS', 'bg-blue-400'),
  ('Pau Saguer Prats', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'PS', 'bg-indigo-400'),
  ('Enrique Sainz Garcia', 'Compres', 'Compres', '', '', '', 'ES', 'bg-violet-400'),
  ('Carles Sala Garriga', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'CS', 'bg-purple-400'),
  ('Joan Sala Rifa', 'Administració Magatzem', 'Magatzem', '', '', '', 'JS', 'bg-fuchsia-400'),
  ('Ramon Sala Busquets', 'Soldador', 'Posta en Marxa', '', '', '', 'RS', 'bg-pink-400'),
  ('Astrid Salgado Padilla', 'Administració Comercial', 'Comercial', '', '', '', 'AS', 'bg-rose-400'),
  ('Basainey Sama', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'BS', 'bg-red-400'),
  ('Tijani Samasa Krubaly', 'Elèctric', 'Posta en Marxa', '', '', '', 'TS', 'bg-orange-400'),
  ('Bilal Samman', 'Mecànic', 'Posta en Marxa', '', '', '', 'BS', 'bg-amber-400'),
  ('Mohamed Samman', 'Mecànic', 'Posta en Marxa', '', '', '', 'MS', 'bg-yellow-400'),
  ('Pau Samper Vila', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'PS', 'bg-lime-400'),
  ('Estefania Sanchez Lopez', 'Administració', 'Administració', '', '', '', 'ES', 'bg-green-400'),
  ('Angel Sanchez Garcia', 'Mecànic', 'Posta en Marxa', '', '', '', 'AS', 'bg-emerald-400'),
  ('Jose Antonio Sanchez Martinez', 'Mecànic', 'Posta en Marxa', '', '', '', 'JS', 'bg-teal-400'),
  ('Raul Sanchez Gonzalez', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'RS', 'bg-cyan-400'),
  ('Sheila Sanchez Espinosa', 'Posta en marxa - Maxpalet', 'Posta en Marxa', '', '', '', 'SS', 'bg-sky-400'),
  ('Marcia Renata Sanchez Robles', 'Compres', 'Compres', '', '', '', 'MS', 'bg-blue-400'),
  ('Manuel Humberto Sánchez Toledo', 'Mecànic', 'Posta en Marxa', '', '', '', 'MS', 'bg-indigo-400'),
  ('Regina Sans Paz', 'Administració RRHH', 'Recursos Humans', '', '', '', 'RS', 'bg-violet-400'),
  ('Cristian Santoro Serrano', 'Elèctric', 'Posta en Marxa', '', '', '', 'CS', 'bg-purple-400'),
  ('Pau Sargatal Juanola', 'Mecànic', 'Posta en Marxa', '', '', '', 'PS', 'bg-fuchsia-400'),
  ('Marcelo Seixas', 'Logística', 'Logística', '', '', '', 'MS', 'bg-pink-400'),
  ('Abulai Semega Sakou', 'Elèctric', 'Posta en Marxa', '', '', '', 'AS', 'bg-rose-400'),
  ('Adrià Serra Casado', 'Posta en marxa - I+D', 'I+D', '', '', '', 'AS', 'bg-red-400'),
  ('David Serra Font', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'DS', 'bg-orange-400'),
  ('Cristina Serra Mendoza', 'Informàtica', 'Informàtica', '', '', '', 'CS', 'bg-amber-400'),
  ('Gerard Serrat Nogue', 'Magatzem', 'Magatzem', '', '', '', 'GS', 'bg-yellow-400'),
  ('Igor Shkira', 'Mecànic', 'Posta en Marxa', '', '', '', 'IS', 'bg-lime-400'),
  ('Lasana Sidebeh Konteh', 'Mecànic', 'Posta en Marxa', '', '', '', 'LS', 'bg-green-400'),
  ('Pablo David Silva Arcos', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'PS', 'bg-emerald-400'),
  ('Bakary Singateh Jambah', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'BS', 'bg-teal-400'),
  ('Arvinder Singh', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'AS', 'bg-cyan-400'),
  ('Avi Singh', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'AS', 'bg-sky-400'),
  ('Haruna Sissoho', 'SAT - Mecànic', 'SAT', '', '', '', 'HS', 'bg-blue-400'),
  ('Hamza Slimani Oukhaleq', 'Elèctric DUAL', 'Posta en Marxa', '', '', '', 'HS', 'bg-indigo-400'),
  ('Jose Antonio Sola Gil', 'OT Mecànica - Envasadores', 'Oficina Tècnica Mecànica', '', '', '', 'JS', 'bg-violet-400'),
  ('David Solà Vidal', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'DS', 'bg-purple-400'),
  ('Eduard Sole Guixeres', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'ES', 'bg-fuchsia-400'),
  ('Marti Soler Bassagañas', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'MS', 'bg-pink-400'),
  ('David Soler Rafart', 'Elèctric', 'Posta en Marxa', '', '', '', 'DS', 'bg-rose-400'),
  ('Estel Soles Figueras', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'ES', 'bg-red-400'),
  ('Antoni Soria Muñoz', 'Posta en marxa - I+D', 'I+D', '', '', '', 'AS', 'bg-orange-400'),
  ('Jordi Soriano Ribas', 'Tècnic comercial', 'Comercial', '', '', '', 'JS', 'bg-amber-400'),
  ('Sergi Soy Clavaguera', 'OT Mecànica - Línies', 'Oficina Tècnica Mecànica', '', '', '', 'SS', 'bg-yellow-400'),
  ('Alberto Soy Cordon', 'SAT - Mecànic', 'SAT', '', '', '', 'AS', 'bg-lime-400'),
  ('Marin Stasiev', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'MS', 'bg-green-400'),
  ('Tanchak Stepan', 'Mecànic', 'Posta en Marxa', '', '', '', 'TS', 'bg-emerald-400'),
  ('Anna Subiros Vehi', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'AS', 'bg-teal-400'),
  ('Isumaila Nyima Sumareh Touray', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'IS', 'bg-cyan-400'),
  ('Abubacarr Sumbundu Mahanera', 'Mecànic', 'Posta en Marxa', '', '', '', 'AS', 'bg-sky-400'),
  ('Miquel Sunyer Roda', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'MS', 'bg-blue-400'),
  ('Gerard Surroca Morote', 'SAT - Mecànic', 'SAT', '', '', '', 'GS', 'bg-indigo-400'),
  ('Saibo Syllah Sillah', 'Elèctric', 'Posta en Marxa', '', '', '', 'SS', 'bg-violet-400'),
  ('Allaye Tamboura Tamboura', 'Mecànic', 'Posta en Marxa', '', '', '', 'AT', 'bg-purple-400'),
  ('Joan Teixidor Buixeda', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'JT', 'bg-fuchsia-400'),
  ('Pere Tenas Llampayas', 'Elèctric', 'Posta en Marxa', '', '', '', 'PT', 'bg-pink-400'),
  ('Genis Tenas Mañas', 'Elèctric', 'Posta en Marxa', '', '', '', 'GT', 'bg-rose-400'),
  ('Daniel Terrones Espinosa', 'Elèctric', 'Posta en Marxa', '', '', '', 'DT', 'bg-red-400'),
  ('Vicky Théroux Mailhot', 'Administració', 'Administració', '', '', '', 'VT', 'bg-orange-400'),
  ('Pol Toldra Fernandez', 'Posta en marxa - I+D', 'I+D', '', '', '', 'PT', 'bg-amber-400'),
  ('Fernando Torna Fernandez', 'Mecànic', 'Posta en Marxa', '', '', '', 'FT', 'bg-yellow-400'),
  ('Fernando Torna Puyol', 'Mecànic', 'Posta en Marxa', '', '', '', 'FT', 'bg-lime-400'),
  ('Marc Torne Juanola', 'OT Elèctrica', 'Oficina Tècnica Elèctrica', '', '', '', 'MT', 'bg-green-400'),
  ('David Torrent Arnall', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'DT', 'bg-emerald-400'),
  ('Joan Torrent Juanola', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'JT', 'bg-teal-400'),
  ('Lluis Torrent Bach', 'Projectes', 'Projectes', '', '', '', 'LT', 'bg-cyan-400'),
  ('Khalil Torres Barreiro', 'OT Mecànica - Màquines', 'Oficina Tècnica Mecànica', '', '', '', 'KT', 'bg-sky-400'),
  ('Sonia Torres Muñoz', 'Administració SAT', 'SAT', '', '', '', 'ST', 'bg-blue-400'),
  ('Laia Tort Vives', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'LT', 'bg-indigo-400'),
  ('Haimadou Touray Juwara', 'Mecànic', 'Posta en Marxa', '', '', '', 'HT', 'bg-violet-400'),
  ('Mohamed Touray Touray', 'Premuntatges mecànics', 'Posta en Marxa', '', '', '', 'MT', 'bg-purple-400'),
  ('Ibrahima Touray Touray', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'IT', 'bg-fuchsia-400'),
  ('Ebrahima Touray Touray', 'Informàtica', 'Informàtica', '', '', '', 'ET', 'bg-pink-400'),
  ('Muhamadou Jaha Touray Saho', 'Elèctric', 'Posta en Marxa', '', '', '', 'MT', 'bg-rose-400'),
  ('Sidi Trawally Camara', 'Mecànic', 'Posta en Marxa', '', '', '', 'ST', 'bg-red-400'),
  ('Mahamadou Trawally Trawally', 'Mecànic DUAL', 'Posta en Marxa', '', '', '', 'MT', 'bg-orange-400'),
  ('Xavier Triado Del Fresno', 'Elèctric', 'Posta en Marxa', '', '', '', 'XT', 'bg-amber-400'),
  ('Sergi Triado Fernandez', 'Projectes', 'Projectes', '', '', '', 'ST', 'bg-yellow-400'),
  ('Mahamado Tunkara Tunkara', 'Elèctric', 'Posta en Marxa', '', '', '', 'MT', 'bg-lime-400'),
  ('Xenia Turon Vilagran', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'XT', 'bg-green-400'),
  ('Lluis Turon Barris', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'LT', 'bg-emerald-400'),
  ('Vladislav Tymoshchuk Kukla', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'VT', 'bg-teal-400'),
  ('Cesar Valdivia Fiallos', 'Administració Magatzem', 'Magatzem', '', '', '', 'CV', 'bg-cyan-400'),
  ('Pau Valeros Rovira', 'OT Mecànica - Maxpalet', 'Oficina Tècnica Mecànica', '', '', '', 'PV', 'bg-sky-400'),
  ('Julio Vanacloig Blazquez', 'Informàtica', 'Informàtica', '', '', '', 'JV', 'bg-blue-400'),
  ('Alex Vasquez Tapia-vera', 'Soldador', 'Posta en Marxa', '', '', '', 'AV', 'bg-indigo-400'),
  ('Pedro Roberto Vásquez Chau', 'Magatzem', 'Magatzem', '', '', '', 'PV', 'bg-violet-400'),
  ('David Vega Fernandez', 'Posta en marxa - DUAL', 'Posta en Marxa', '', '', '', 'DV', 'bg-purple-400'),
  ('Alessandro Venosa', 'Tècnic comercial', 'Comercial', '', '', '', 'AV', 'bg-fuchsia-400'),
  ('Jordi Verdaguer Brugues', 'Mecànic', 'Posta en Marxa', '', '', '', 'JV', 'bg-pink-400'),
  ('Joan Verdaguer Planaguma', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'JV', 'bg-rose-400'),
  ('Montserrat Verdaguer Serral', 'Validació Ofertes - Costos', 'Costos', '', '', '', 'MV', 'bg-red-400'),
  ('Parikshit Verma', 'Posta en marxa - I+D', 'I+D', '', '', '', 'PV', 'bg-orange-400'),
  ('Sergi Vidal Mares', 'Posta en marxa - Línies', 'Posta en Marxa', '', '', '', 'SV', 'bg-amber-400'),
  ('Alba Vidal Vila', 'Validació Ofertes - Costos', 'Costos', '', '', '', 'AV', 'bg-yellow-400'),
  ('Julia Vila Xirgu', 'Administració RRHH', 'Recursos Humans', '', '', '', 'JV', 'bg-lime-400'),
  ('Miquel Vila Cullell', 'Posta en marxa', 'Posta en Marxa', '', '', '', 'MV', 'bg-green-400'),
  ('Pau Vilanova Corrales', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'PV', 'bg-emerald-400'),
  ('Marc Vilanova Corrales', 'OT Mecànica - Pick & Place', 'Oficina Tècnica Mecànica', '', '', '', 'MV', 'bg-teal-400'),
  ('Adela Vilanova Fabrega', 'Tècnic comercial', 'Comercial', '', '', '', 'AV', 'bg-cyan-400'),
  ('Lluis Vilanova Alzamora', 'Qualitat i seguretat', 'Qualitat i Seguretat', '', '', '', 'LV', 'bg-sky-400'),
  ('David Vilanova Fàbrega', 'Projectes', 'Projectes', '', '', '', 'DV', 'bg-blue-400'),
  ('Francisco Javier Vilanova Alzamora', 'Tècnic comercial', 'Comercial', '', '', '', 'FV', 'bg-indigo-400'),
  ('Aniol Vilar Guitart', 'Posta en marxa - Màquines', 'Posta en Marxa', '', '', '', 'AV', 'bg-violet-400'),
  ('Aniol Vilaregut Argerich', 'OT Mecànica - DUAL', 'Oficina Tècnica Mecànica', '', '', '', 'AV', 'bg-purple-400'),
  ('Eric Joaquin Villena Ninapaitan', 'Posta en marxa - I+D', 'I+D', '', '', '', 'EV', 'bg-fuchsia-400'),
  ('Arnau Viñals Babot', 'Informàtica', 'Informàtica', '', '', '', 'AV', 'bg-pink-400'),
  ('Tomasz Wiktor Witkowiak', 'SAP', 'SAP', '', '', '', 'TW', 'bg-rose-400'),
  ('Philipp Zabeline', 'Tècnic comercial', 'Comercial', '', '', '', 'PZ', 'bg-red-400'),
  ('Ismael Zekriti Miro', 'Elèctric', 'Posta en Marxa', '', '', '', 'IZ', 'bg-orange-400'),
  ('Enrui Zhou', 'Posta en marxa - I+D', 'I+D', '', '', '', 'EZ', 'bg-amber-400'),
  ('Roxana Zoitanu', 'Administració Comercial', 'Comercial', '', '', '', 'RZ', 'bg-yellow-400');